// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rfcusngoutymilmpilez.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJmY3VzbmdvdXR5bWlsbXBpbGV6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5NDI5MTgsImV4cCI6MjA2NDUxODkxOH0.0lp56WZvtUZgla4_GO_sE0Bm24gNHtXeSRbgHzSOJso";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);